apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gif-app.fullname" . }}-flask-config
  labels:
    app: flask-app
    {{- include "gif-app.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ include "gif-app.fullname" . }}-mysql.{{ .Release.Namespace }}.svc.cluster.local"
  DB_PORT: "{{ .Values.mysql.service.port }}"
  DB_NAME: "{{ .Values.database.name }}"
  DB_USER: "{{ .Values.database.user }}"
  DB_PASSWORD: "{{ .Values.database.password }}"
  FLASK_ENV: "development"
  PORT: "{{ .Values.flask.service.targetPort }}"