# Application Configuration
flask:
  image:
    repository: orelneto/flaskapp_with_db_motogpgif
    tag: "2.0"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 5000
  replicas: 1

mysql:
  image:
    repository: mysql
    tag: "5.7"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  replicas: 1
  persistence:
    enabled: true
    storageClass: "hostpath"
    size: 1Gi
  
# Database Configuration
database:
  name: mydatabase
  user: root
  password: rootpassword
  rootHost: "%"

# ConfigMaps and Init Scripts
initScript:
  enabled: true

# Monitoring Configuration
monitoring:
  prometheus:
    image:
      repository: prom/prometheus
      tag: v2.30.3
    service:
      type: NodePort
  grafana:
    image:
      repository: grafana/grafana
      tag: 8.2.2
    service:
      type: NodePort
    adminPassword: admin