apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
  labels:
    app: flask-app
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - port: {{ .Values.flask.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
      {{- if and (eq .Values.flask.service.type "NodePort") .Values.flask.service.nodePort }}
      nodePort: {{ .Values.flask.service.nodePort }}
      {{- end }}
  selector:
    app: flask-app