apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
  labels:
    app: flask-app
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - name: http
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.flask.service.type "NodePort") .Values.flask.service.nodePort }}
      nodePort: {{ .Values.flask.service.nodePort }}
      {{- end }}
    {{- if .Values.serviceMonitor.enabled }}
    - name: metrics
      port: 9110
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    app: flask-app
