apiVersion: v1
kind: Service
metadata:
  name: {{ include "gif-app.fullname" . }}-flask
  labels:
    {{- include "gif-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - name: http
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.flask.service.type "NodePort") .Values.flask.service.nodePort }}
      nodePort: {{ .Values.flask.service.nodePort }}
      {{- end }}
    {{- if .Values.serviceMonitor.enabled }}
    - name: metrics
      port: 9110
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.flask.service.extraPorts }}
    {{- range .Values.flask.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}
    {{- end }}
  selector:
    app: flask-app