apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  type: {{ .Values.monitoring.prometheus.service.type }}
  selector:
    app: flask-app
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  type: {{ .Values.monitoring.grafana.service.type }}
  selector:
    app: flask-app
  ports:
    - port: 3000
      targetPort: 3000