name: Terraform AKS Deployment

on:
  push:
    branches: [ main, ci_and_cd ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:  # Allows manual trigger

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Format
      working-directory: ./terraform
      run: terraform fmt -check || true

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -out=tfplan
      
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve tfplan
    
    - name: Get AKS Credentials
      run: |
        # Install Azure CLI
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        
        # Login to Azure with service principal
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
        
        # Use fixed values for resource group and cluster name
        RESOURCE_GROUP="orel-neto-project"
        CLUSTER_NAME="gifapp-aks"
        
        # Save Kubernetes credentials
        mkdir -p ~/.kube
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --file kubeconfig.yaml
        echo "Kubeconfig saved to kubeconfig.yaml"
    
    - name: Trigger CI Pipeline
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_PAT }}
        event-type: start-ci-pipeline